language: go
sudo: false
go:
  - "1.12.x"

git:
  depth: 1

env:
  - TESTS="-race -v -bench=. -coverprofile=coverage.txt -covermode=atomic"
  - TESTS="-race -v ./..."

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libunbound-dev

script:
  - go test $TESTS

after_success:
  - bash <(curl -s https://codecov.io/bash)
